create table ASSETLOCATION_TEST (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, status_code varchar2(255 char), timestamp timestamp, typecode varchar2(255 char), asset_id number(19,0), primary key (id))
create table ASSET_TEST (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, attachmentDesc varchar2(255 char), guid varchar2(255 char) not null, name varchar2(255 char), primary key (id), unique (guid))
create table COMM_ID_HEADER (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, mac varchar2(32 char), server_no number(10,0), primary key (id))
comment on table COMM_ID_HEADER is 'ID header info'
create table COMM_MENU (id number(10,0) not null, content varchar2(32 char), from_src varchar2(1 char), menu_group varchar2(50 char), icon_url varchar2(64 char), is_valid number(19,0), layout_template varchar2(32 char), name varchar2(32 char), parent_id number(10,0), remark varchar2(100 char), sub_menu_from_way varchar2(32 char), menu_type varchar2(32 char), type_code varchar2(16 char), primary key (id))
create table COMM_POJO_ID (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, item varchar2(96 char), max_id number(19,0), next_id number(19,0), is_useup number(1,0), header_id varchar2(255 char) not null, primary key (id))
comment on table COMM_POJO_ID is 'POJO ID'
create table EMAIL (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, attachment blob, attachment_name varchar2(255 char), body clob not null, from_address varchar2(255 char), host varchar2(255 char), inline_html char(1 char), loop_counter number(10,0), sent char(1 char), subject varchar2(255 char) not null, to_address varchar2(255 char) not null, primary key (id))
create table LOCATION (id number(19,0) not null, typecode varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, addr_line1 varchar2(255 char), addr_line2 varchar2(128 char) not null, city varchar2(255 char), country varchar2(255 char), lat_coor varchar2(255 char), lon_coor varchar2(255 char), state varchar2(255 char), text varchar2(255 char), primary key (id, typecode))
create table MDM_ReceiveRecord (id number(19,0) not null, changeType varchar2(255 char), code varchar2(255 char), entityName varchar2(255 char), revision number(10,0) not null, status varchar2(255 char), subscriber varchar2(255 char), primary key (id))
create table MDM_SYNCRECORD (id number(19,0) not null, entityIdString varchar2(255 char), entityIdType varchar2(255 char), entityName varchar2(255 char), revId number(10,0) not null, revisionType varchar2(255 char), status varchar2(255 char), type varchar2(255 char), updateBy varchar2(255 char), primary key (id))
create table PASSWORD_RESET_INFO (uuid varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, userName varchar2(255 char), primary key (uuid))
create table ProductMaster_flexFields (ProductMaster_id varchar2(255 char) not null, flexFields varchar2(255 char), flexFields_KEY varchar2(255 char), primary key (ProductMaster_id, flexFields_KEY))
create table REVCHANGES (REV number(10,0) not null, ENTITYNAME varchar2(255 char))
create table REVISIONS (id number(10,0) not null, timestamp number(19,0) not null, username varchar2(255 char), version varchar2(255 char), primary key (id))
create table TEST_NON_DATAOBJECT (id number(19,0) not null, primary key (id))
create table TEST_NO_LISTENER (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, primary key (id))
create table UNITTEST_ACL_CHILD_ENTITY (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, date_property timestamp, dbl_property double precision, long_property number(19,0), str_property varchar2(255 char), parent_id varchar2(255 char), primary key (id))
create table UNITTEST_ACL_ENTITY (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, date_property timestamp, dbl_property double precision, long_property number(19,0), str_property varchar2(255 char), primary key (id))
create table UT_DOMAIN (name varchar2(64 char) not null, id varchar2(128 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, primary key (name, id))
create table Users (user_name varchar2(64 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, account_non_expired char(1 char) not null, account_non_locked char(1 char) not null, addr_line1 varchar2(128 char), addr_line2 varchar2(128 char), bemployee_id number(19,0), bphone varchar2(255 char), city varchar2(64 char), country varchar2(64 char), credentials_non_expired char(1 char) not null, email varchar2(64 char) not null unique, employee_id number(19,0), enabled char(1 char) not null, full_name varchar2(64 char) not null, localeString varchar(20) default 'en' not null, mobile varchar2(16 char), password varchar2(255 char) not null, password_temporary char(1 char) not null, postalcode varchar2(32 char), state varchar2(64 char), user_grp number(19,0), org_id varchar2(255 char), primary key (user_name), unique (email))
create table acl_expr_association (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, resource_name varchar2(255 char) not null, expression_id number(19,0) not null, permission_id varchar2(255 char) not null, role_id number(19,0) not null, primary key (id))
create table acl_expression (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, description varchar2(1024 char) not null, expression varchar2(2048 char) not null, expression_name varchar2(255 char) not null, primary key (id), unique (expression_name))
create table comm_role_menu_associations (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, child_role_id number(19,0), menu_id number(10,0), role_id number(19,0), primary key (id))
create table comm_roles_menus (roles_id number(19,0) not null, menus_id number(10,0) not null, primary key (roles_id, menus_id))
create table filter_expressions (id number(19,0) not null, lower_limit varchar2(255 char), name varchar2(255 char) not null, search_operator varchar2(255 char) not null, upper_limit varchar2(255 char), primary key (id))
create table organizations (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, code varchar2(255 char) not null unique, name varchar2(64 char) not null, points varchar2(255 char), parent_id varchar2(255 char), primary key (id))
create table permissions (name varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, description varchar2(255 char), display_name varchar2(255 char), protected_resource varchar2(255 char) not null, resource_type varchar2(255 char) not null, user_operation number(10,0) not null, primary key (name), unique (user_operation, protected_resource))
create table role_permission_associations (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, child_role_id number(19,0), permission_id varchar2(255 char), role_id number(19,0), primary key (id))
create table roles (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, name varchar2(255 char) not null, org_id varchar2(255 char), parent_id number(19,0), primary key (id), unique (name))
create table roles_permissions (roles_id number(19,0) not null, permissions_name varchar2(255 char) not null, primary key (roles_id, permissions_name))
create table search_criteria (id number(19,0) not null, default_criteria char(1 char), display_key varchar2(255 char) not null, entity_name varchar2(255 char) not null, name varchar2(255 char) not null, visible char(1 char), primary key (id), unique (entity_name, name))
create table sort_expressions (id number(19,0) not null, ascending char(1 char), name varchar2(255 char) not null, primary key (id))
create table srchcriteria_fltrexpr (search_criteria_id number(19,0) not null, filterExpressions_id number(19,0) not null, unique (filterExpressions_id))
create table srchcriteria_sortexpr (search_criteria_id number(19,0) not null, sortExpressions_id number(19,0) not null, unique (sortExpressions_id))
create table test_categories (category_name varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, code varchar2(255 char) not null unique, category_description varchar2(255 char) not null, primary key (category_name))
create table test_gen_article (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, big_decimal number(19,2), big_integer number(19,2), boolean_primitive number(1,0), boolean_wrapper number(1,0), date_column timestamp, double_primitive double precision, double_wrapper double precision, float_primitive float, float_wrapper float, int_primitive number(10,0), int_wrapper number(10,0), long_primitive number(19,0), long_wrapper number(19,0), name varchar2(255 char) not null unique, primary key (id))
create table test_product_masters (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, config_descriminator varchar2(255 char), name varchar2(255 char) not null, category_name varchar2(255 char) not null, uom varchar2(255 char) not null, primary key (id))
create table test_products (id varchar2(20 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, name varchar2(255 char) not null, physicaltag varchar2(255 char), tag1 varchar2(255 char) not null, tag2 varchar2(255 char), tag3 varchar2(255 char), manufacturer_id varchar2(255 char) not null, product_master_id varchar2(255 char) not null, primary key (id))
create table test_uom (name varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, i18n_name varchar2(255 char) not null, primary key (name))
create table users_roles (users_user_name varchar2(64 char) not null, roles_id number(19,0) not null, primary key (users_user_name, roles_id))
alter table ASSETLOCATION_TEST add constraint FKD7BD0E0CACC52FBA foreign key (asset_id) references ASSET_TEST
alter table COMM_POJO_ID add constraint FKA8470183FF829E0C foreign key (header_id) references COMM_ID_HEADER
alter table ProductMaster_flexFields add constraint FKE2AB3900B19BFC3A foreign key (ProductMaster_id) references test_product_masters
alter table REVCHANGES add constraint FK727428C02ECD108A foreign key (REV) references REVISIONS
alter table UNITTEST_ACL_CHILD_ENTITY add constraint FK45EE93444BB58F93 foreign key (parent_id) references UNITTEST_ACL_ENTITY
alter table Users add constraint FK4E39DE8FF191F53 foreign key (org_id) references organizations
alter table acl_expr_association add constraint FK24477C4C49DE09C4 foreign key (role_id) references roles
alter table acl_expr_association add constraint FK24477C4C42CCDFA4 foreign key (permission_id) references permissions
alter table acl_expr_association add constraint FK24477C4C2AD46923 foreign key (expression_id) references acl_expression
alter table comm_role_menu_associations add constraint FK502F75FC306F7524 foreign key (menu_id) references COMM_MENU
alter table comm_role_menu_associations add constraint FK502F75FC3EC8C9A1 foreign key (child_role_id) references roles
alter table comm_role_menu_associations add constraint FK502F75FC49DE09C4 foreign key (role_id) references roles
alter table comm_roles_menus add constraint FKF3CEA23FD3DB0F6F foreign key (menus_id) references COMM_MENU
alter table comm_roles_menus add constraint FKF3CEA23FE7F6821D foreign key (roles_id) references roles
alter table organizations add constraint FK8258B9A0B69F27CD foreign key (parent_id) references organizations
alter table role_permission_associations add constraint FK9CF783B93EC8C9A1 foreign key (child_role_id) references roles
alter table role_permission_associations add constraint FK9CF783B949DE09C4 foreign key (role_id) references roles
alter table role_permission_associations add constraint FK9CF783B942CCDFA4 foreign key (permission_id) references permissions
alter table roles add constraint FK67A8EBDFF191F53 foreign key (org_id) references organizations
alter table roles add constraint FK67A8EBD73332510 foreign key (parent_id) references roles
alter table roles_permissions add constraint FK250AE02E7F6821D foreign key (roles_id) references roles
alter table roles_permissions add constraint FK250AE024F8AB7F foreign key (permissions_name) references permissions
alter table srchcriteria_fltrexpr add constraint FKBA27D015411B4F1 foreign key (search_criteria_id) references search_criteria
alter table srchcriteria_fltrexpr add constraint FKBA27D015CCE57DFD foreign key (filterExpressions_id) references filter_expressions
alter table srchcriteria_sortexpr add constraint FK9BFC46EF411B4F1 foreign key (search_criteria_id) references search_criteria
alter table srchcriteria_sortexpr add constraint FK9BFC46EFDE7EE5BD foreign key (sortExpressions_id) references sort_expressions
alter table test_product_masters add constraint FK6CBD6D5445A13E2A foreign key (category_name) references test_categories
alter table test_product_masters add constraint FK6CBD6D54B5E36E26 foreign key (uom) references test_uom
alter table test_products add constraint FK7A09C271225654F9 foreign key (product_master_id) references test_product_masters
alter table test_products add constraint FK7A09C2715423E746 foreign key (manufacturer_id) references organizations
alter table users_roles add constraint FKF6CCD9C6E7F6821D foreign key (roles_id) references roles
alter table users_roles add constraint FKF6CCD9C6A4BB6C9D foreign key (users_user_name) references Users
create sequence ASSETLOCATION_TEST_SEQ_DB
create sequence ASSET_TEST_SEQ_DB
create sequence TEST_NON_DATAOBJECT_SEQ_DB
create sequence TEST_NO_LISTENER_SEQ_DB
create sequence hibernate_sequence
create sequence test_gen_article_seq_db
