package com.digitnexus.core.test.dataobjects;




import javax.persistence.Embeddable;


/**
 * LocationId generated by hbm2java
 */

@Embeddable
public class LocationId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long id;
	private String typecode;

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}
	
	public boolean equals(Object other) {
		
		if (!(other instanceof LocationId))
			return false;
		LocationId castOther = (LocationId) other;
		
		return (this.id==castOther.id) && (this.typecode.equals(castOther.getTypecode()));

		
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + new Long(id).intValue();
		result = 37 * result + getTypecode().hashCode();
		return result;
	}

}
